#version: '3.8'

# ----------------------------
# Docker Volumes
# ----------------------------
volumes:
  es_data:        # Persist Elasticsearch indices across restarts
  portainer_data: # Persist Portainer’s SQLite data
  filebeat_data:  # Stores Filebeat registry

# ----------------------------
# Shared Network
# ----------------------------
networks:
  observability:
    driver: bridge

services:

  # ----------------------------------------
  # Flask Microservice: TechSavvyRC
  # ----------------------------------------
  techsavvyrc-app:
    build: ./techsavvyrc
    container_name: techsavvyrc-app
    ports:
      - 8000:8000
    volumes:
      - ./techsavvyrc/logs:/app/log
    environment:
      # OTLP endpoint for spans
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - otel-collector
      - apm-server
      - prometheus
    logging:
      driver: "json-file"
    networks:
      - observability

  # ----------------------------------------
  # Elasticsearch: Stores logs, metrics, and traces
  # ----------------------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - observability

  # ----------------------------------------
  # APM Server: Accepts traces/logs from OTel collector and agents
  # ----------------------------------------
  apm-server:
    image: docker.elastic.co/apm/apm-server:${ELK_VERSION}
    container_name: apm-server
    ports:
      - 8200:8200
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - observability

  # ----------------------------------------
  # Kibana: Visualizes Elasticsearch data
  # ----------------------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - observability

  # ----------------------------------------
  # Metricbeat: Collects metrics (Docker, Host, etc.)
  # ----------------------------------------
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    container_name: metricbeat
    user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - observability

  # ----------------------------------------
  # Filebeat: Collects logs from Docker containers
  # ----------------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./techsavvyrc/logs:/usr/share/filebeat/logs:ro 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeat_data:/usr/share/filebeat/data
      # - ./filebeat/modules.d:/usr/share/filebeat/modules.d:ro
    depends_on:
      - logstash
    networks:
      - observability

  # ----------------------------------------
  # Logstash: Parses and ships logs to Elasticsearch
  # ----------------------------------------
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeat_data:/usr/share/filebeat/data
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
    networks:
      - observability
    environment:
      - LS_JAVA_OPTS=-Xms2g -Xmx2g

  # ----------------------------------------
  # Prometheus: Scrapes metrics from app and (optionally) OTel Collector
  # ----------------------------------------
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    networks:
      - observability

  # ----------------------------------------
  # Grafana: Visualizes Prometheus data
  # ----------------------------------------
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - observability

  # ----------------------------------------
  # OpenTelemetry Collector: Accepts OTLP spans
  # ----------------------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel/otel-config.yaml:/etc/otelcol/config.yaml:ro
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    networks:
      - observability

  # ----------------------------------------
  # Portainer: Docker GUI
  # ----------------------------------------
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - observability
