# Multi-line comments for clarity:
# This Prometheus configuration file defines scraping jobs.
# It scrapes metrics from the Flask app running at port 8000.

global:
  scrape_interval: 15s  # How frequently to scrape targets by default.

scrape_configs:
  - job_name: 'techsavvyrc-app'
    static_configs:
      - targets: ['techsavvyrc-app:8000']  # Endpoint exposing metrics via prometheus_client
