receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: techsavvyrc

  otlp/elastic:
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true
    headers:
      # Authorization: "Bearer <your_token_here>"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus, otlp/elastic]

    traces:
      receivers: [otlp]
      exporters: [otlp/elastic]

